# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae499ec21f0db3938ff72b8d50d19963dd92075944e24004a901f1cb600c0be4ad8edc389b6e76658cb0936dbf77fa2bd9a3ee1a0c729775b5b3cca543f013bd

test:
  secret_key_base: 78e5351714138a2318c7cb1c43f4e348f12d21bb495d856f629ee7909af6c52977c87198034d94f63a030f6578f5ddaae6f13b526de4caf22a0e31a2949ec382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
